# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_gen import game_pb2 as game__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/game.Game/JoinGame',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.JoinGameReply.FromString,
                )
        self.GetState = channel.unary_unary(
                '/game.Game/GetState',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.GetStateReply.FromString,
                )
        self.GetStateStream = channel.unary_stream(
                '/game.Game/GetStateStream',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                )
        self.PostTankEvent = channel.unary_unary(
                '/game.Game/PostTankEvent',
                request_serializer=game__pb2.PostTankEventRequest.SerializeToString,
                response_deserializer=game__pb2.Empty.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostTankEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.JoinGameReply.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.GetStateReply.SerializeToString,
            ),
            'GetStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStateStream,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'PostTankEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PostTankEvent,
                    request_deserializer=game__pb2.PostTankEventRequest.FromString,
                    response_serializer=game__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/JoinGame',
            game__pb2.Empty.SerializeToString,
            game__pb2.JoinGameReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/GetState',
            game__pb2.Empty.SerializeToString,
            game__pb2.GetStateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/game.Game/GetStateStream',
            game__pb2.Empty.SerializeToString,
            game__pb2.GameState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostTankEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/PostTankEvent',
            game__pb2.PostTankEventRequest.SerializeToString,
            game__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
