# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"\xe1\x01\n\x04Tank\x12\r\n\x05pos_x\x18\x01 \x01(\x01\x12\r\n\x05pos_y\x18\x02 \x01(\x01\x12\x10\n\x08velocity\x18\x03 \x01(\x01\x12\r\n\x05\x61ngle\x18\x04 \x01(\x01\x12\x0e\n\x06health\x18\x05 \x01(\x01\x12\x15\n\rbullet_damage\x18\x06 \x01(\x01\x12\x17\n\x0f\x62ullet_velocity\x18\x07 \x01(\x01\x12\x16\n\x0eshoot_cooldown\x18\x08 \x01(\x01\x12\x17\n\x0flast_shoot_time\x18\t \x01(\x01\x12\n\n\x02id\x18\n \x01(\t\x12\r\n\x05width\x18\x0b \x01(\x01\x12\x0e\n\x06height\x18\x0c \x01(\x01\"v\n\x06\x42ullet\x12\r\n\x05pos_x\x18\x01 \x01(\x01\x12\r\n\x05pos_y\x18\x02 \x01(\x01\x12\r\n\x05\x61ngle\x18\x03 \x01(\x01\x12\x10\n\x08velocity\x18\x04 \x01(\x01\x12\x0e\n\x06\x64\x61mage\x18\x05 \x01(\x01\x12\r\n\x05width\x18\x06 \x01(\x01\x12\x0e\n\x06height\x18\x07 \x01(\x01\" \n\rJoinGameReply\x12\x0f\n\x07tank_id\x18\x01 \x01(\t\"E\n\tGameState\x12\x19\n\x05tanks\x18\x01 \x03(\x0b\x32\n.game.Tank\x12\x1d\n\x07\x62ullets\x18\x02 \x03(\x0b\x32\x0c.game.Bullet\"4\n\rGetStateReply\x12#\n\ngame_state\x18\x01 \x01(\x0b\x32\x0f.game.GameState\"G\n\x14PostTankEventRequest\x12\x1e\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x0f.game.TankEvent\x12\x0f\n\x07tank_id\x18\x02 \x01(\t\"\x07\n\x05\x45mpty*^\n\tTankEvent\x12\t\n\x05SHOOT\x10\x00\x12\x10\n\x0cMOVE_FORWARD\x10\x01\x12\x11\n\rMOVE_BACKWARD\x10\x02\x12\x0f\n\x0bROTATE_LEFT\x10\x03\x12\x10\n\x0cROTATE_RIGHT\x10\x04\x32\xce\x01\n\x04Game\x12,\n\x08JoinGame\x12\x0b.game.Empty\x1a\x13.game.JoinGameReply\x12,\n\x08GetState\x12\x0b.game.Empty\x1a\x13.game.GetStateReply\x12\x30\n\x0eGetStateStream\x12\x0b.game.Empty\x1a\x0f.game.GameState0\x01\x12\x38\n\rPostTankEvent\x12\x1a.game.PostTankEventRequest\x1a\x0b.game.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TANKEVENT']._serialized_start=609
  _globals['_TANKEVENT']._serialized_end=703
  _globals['_TANK']._serialized_start=21
  _globals['_TANK']._serialized_end=246
  _globals['_BULLET']._serialized_start=248
  _globals['_BULLET']._serialized_end=366
  _globals['_JOINGAMEREPLY']._serialized_start=368
  _globals['_JOINGAMEREPLY']._serialized_end=400
  _globals['_GAMESTATE']._serialized_start=402
  _globals['_GAMESTATE']._serialized_end=471
  _globals['_GETSTATEREPLY']._serialized_start=473
  _globals['_GETSTATEREPLY']._serialized_end=525
  _globals['_POSTTANKEVENTREQUEST']._serialized_start=527
  _globals['_POSTTANKEVENTREQUEST']._serialized_end=598
  _globals['_EMPTY']._serialized_start=600
  _globals['_EMPTY']._serialized_end=607
  _globals['_GAME']._serialized_start=706
  _globals['_GAME']._serialized_end=912
# @@protoc_insertion_point(module_scope)
